name: Build and Push Docker Image

on:
  push:
    branches:
      - master 


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get current date
        id: date
        run: echo "today=$(date +'%Y.%m.%d')" >> $GITHUB_ENV
      -
        name: Build and push DCU-langchain
        uses: docker/build-push-action@v6
        with:
          context: .
          file: .Dockerfile
          push: true
          tags: |
            yidhra/DCU-langchain:latest
            yidhra/DCU-langchain:${{ env.today }}
